name: Spaced Revision (Notify)

on:
  schedule:
    # 01:30 UTC = 07:00 IST
    - cron: "30 1 * * *"
  workflow_dispatch:

permissions:
  contents: write 

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Debug tracker file
        run: cat revision_tracker.json

      - name: Send Telegram notification
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python .github/scripts/notify.py

      - name: Commit tracker updates
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(srs): update tracker pending flags"
          commit_user_name: "srs-bot"
          commit_user_email: "srs-bot@users.noreply.github.com"

